### ISSUE TITLE
Unable to parse YAML config as Json

### ISSUE THREAD

**Issue by WizMe-M** [meshapi/grpc-api-gateway#16]
# Context

I use local plugin from [last](https://github.com/meshapi/grpc-api-gateway/releases/tag/v0.0.11) release and `buf.gen.yaml` my config is:
```yaml
inputs:
- directory: .
  paths:
  - module\api\service\ 

plugins:
  - local: ../../third_party/protoc-gen-openapiv3.exe # current dir is proto root
    out: gen/swagger/v3
    opt:
      - openapi_config=my_api_config.yaml
```

# Actual behavior

When I call `buf generate --template my_buf.gen.yaml` (from proto root dir) openapi plugin responds with error:
```
protoc-gen-openapiv3.exe: failed to load global OpenAPI config file: failed to JSON marshal content: json: unsupported type: map[interface {}]interface {}
```

# Expected behavior

No error and merged swagger for all services in `module/api/service` was generated
