### ISSUE TITLE
BUG: output format JSON generates invalid security scope for empty array

### ISSUE THREAD

**Issue by WizMe-M** [meshapi/grpc-api-gateway#17]
# Reproduce 

<details>

<summary>Minimal repro structure</summary>

![image](https://github.com/user-attachments/assets/46b2f0d7-5163-4fb4-a77e-a26be69646a1)

</details>

1. Create `foo.proto`:
```proto
syntax = "proto3";
package foo;

option go_package = 'example.com/example/foo';

service FooService {
    rpc FooBar(FooRequest) returns (FooResponse);
  }

message FooRequest {
}

message FooResponse {
}
```

2. Add `api_openapi.yaml`:
```yaml
openapi:
  document:
    components:
      security_schemes:
        MyJwtBearer:
          type: http
          name: Authorization
          in: header
          scheme: bearer
          bearer_format: JWT

  services:
    - selector: 'foo.FooService'
      methods:
        FooBar:
          security:
            - name: MyJwtBearer
              scopes: [ ] # core setting

gateway:
  endpoints:
    - selector: 'foo.FooService.FooBar'
      post: '/foo'
      body: '*'
```

3. Add `buf.gen.yaml`:
```yaml
version: v2

plugins: 
  - local: ../protoc-gen-openapiv3 # or remote to buf.build
    out: ../gen
    opt:
      - openapi_config=api_openapi.yaml
      - gateway_config=api_openapi.yaml
      - output_format=json # core setting
```
4. Run `buf generate`
5. Change `output_format` to `json`
6. Run `buf generate` again

# Actual behavior 

<details>

<summary>Generated files</summary>

### YAML

```yaml
paths:
  /foo:
    post:
      ...
      security:
        - MyJwtBearer: []
```

### JSON

```json
  "paths": {
    "/foo": {
      "post": {
        ....
        "security": [
          {
            "MyJwtBearer": null
          }
        ]
      }
```
</details>

If we take a look into gemerated apidocs we will see that:
- yaml-specification has valid scope (`[]`) for `MyJwtBearer` in `/foo` endpoint
- json-specification has `null` scope for `MyJwtBearer` in `/foo` endpoint

If we check them out in [Swagger Editor](https://editor-next.swagger.io/) we will see, that json spec (with null scope) is invalid and editor misses auth for the endpoint.

<details>

<summary>Broken auth img</summary>

![image](https://github.com/user-attachments/assets/47e31cca-7165-42c7-a502-66a0973467fd)

</details>

# Expected behavior 

Both `yaml` and `json` specs (output formats) will have the same identical scope value (empty array `[]`)
