### ISSUE TITLE
BUG: wildcard route conflicts with existing children in path

### ISSUE THREAD

**Issue by WizMe-M** [meshapi/grpc-api-gateway#21]
Hi, @peymanmortazavi, I've encountered a new error :)
My REST API definition has endpoints like this:
```yaml
paths:
  /v1/my/route:
    post:
    get:
  /v1/my/route/{path_param}:
    get:
    put:
    delete:
  /v1/my/route/{path_param}/other:
   patch:
   put:
```

So when I'm trying to `RegisterServiceHandlerFromEndpoint` that handles these routes I got `panic` and my app fails with error:
```
panic: wildcard route ':path_param' conflicts with existing children in path '/v1/my/route/:path_param'
```

As I see, this is an error within `httprouter` lib. 
Similiar issue was encountered in gin lib: https://github.com/gin-gonic/gin/issues/1681

What can I do to fix that?
