### ISSUE TITLE
How to remove some endpoints out of resulting OpenAPI yaml

### ISSUE THREAD

**Issue by WizMe-M** [meshapi/grpc-api-gateway#22]
# Context

I have two different openapi configs representing public and private parts of API.
Private part have full definition of services, while public has only several services included.
I also use local configs to not duplicate gateway-endpoints configuration.

I use buf.gen with plugin config:
```
plugins:
  - local: protoc-gen-openapiv3
    out: gen/swagger/v3
    opt:
      - config_search_path=config
      - openapi_config=public_openapi.yaml
      - gateway_config_pattern={{.Path}}
      - disable_service_tags=true
      - output_mode=merge
      - output_filename=public
      - output_format=yaml
      - warn_on_broken_selectors=true
```

# Expected behavior:

Only annotated in openapi config services' endpoints will be included in resulting `public_openapi.yaml`

# Actual behavior:

All services listed in resulting yaml.  
However private endpoints will be listed without tags (in swagger.editor under 'default' section)

# What solutions could be

1. Duplicate gateway configs for private part with special suffix (`gateway_config_pattern={{.Path}}_private`)
The easiest one - no code changes, but that will lead to duplication of gateway configs and potential contradiction between public and private gateway configs.

2. Do not include untagged in openapi config endpoints
```
    - selector: '.api.service.v1.PrivateService'
      methods:
        PublicEndpoint:
          tags:
            - Public # <-- this tag will show that this endpoint should be included
        PrivateEndpoint:
           # no tag here so this endpoint should be hidden
```
So we could specify parameter in buf.gen.yaml like `include_untagged_endpoints` with value `false` to hide private endpoints out of resulting `public_openapi.yaml`

3. Generate dependent on visibility restriction
service.proto:
```
service PublicService {
  rpc Foo(FooRequest) returns (FooResponse) {
    option (google.api.api_visibility).restriction = "INTERNAL"; // indicate that this endpoint is internal
  }
}

service PrivateService {
  option (google.api.api_visibility).restriction = 'INTERNAL'; // all endpoints in this service are internal

  ....
}
```
And in buf.gen.yaml we could specify option `visibility_restriction=PUBLIC,INTERNAL` (or nothing for all endpoints)

**Comment by WizMe-M** [comment]
Hi, there @peymanmortazavi :) I'm back again with new questions

**Comment by peymanmortazavi** [comment]
Okay so it looks like if you're working with a buf.yaml file, you can do something like this:

````yaml
plugins:
  - local: protoc-gen-openapiv3
    out: gen/swagger/v3
    opt:
      - config_search_path=config
      - openapi_config=public_openapi.yaml
      - gateway_config_pattern={{.Path}}
      - disable_service_tags=true
      - output_mode=merge
      - output_filename=public
      - output_format=yaml
      - warn_on_broken_selectors=true
      - visibility_selectors=INTERNAL,EXTERNAL
````

Note that the visibility selector includes any method that has either of those labels OR methods that do not specify any visibility restriction.

If you want to exclude `INTERNAL` for instance, you should include a non-empty list that does not contain INTERNAL. Say `PUBLIC`. Then only methods that have `PUBLIC` or no restriction at all would get selected.
