### ISSUE TITLE
Support for Buf

### ISSUE THREAD

**Issue by Loschcode** [meshapi/grpc-api-gateway#34]
Hi,

First of all, thank you very much for putting time and effort into something that is not easy to build. I'm developing a project that requires [gRPC Gateway](https://github.com/grpc-ecosystem/grpc-gateway) to work, but after some research, I realized they had no intention of supporting OpenAPI v3, which I find quite ridiculous given their fame.

I want to try your solution, but I use Buf and wish to keep it that way. I'm not sure how that works with them, but it would be awesome if your system supported them.

```yaml
version: v2
name: github.com/linkbreakers-com/api
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

You can see `buf.build/grpc-ecosystem/grpc-gateway` and this allows you to configure easily the generation without going through `protoc-gen`

**Comment by peymanmortazavi** [comment]
@Loschcode thanks for creating this issue. You can definitely use buf, I use buf and this is what my config looks like:

```yaml
version: v1
deps:
  - "buf.build/meshapi/grpc-api-gateway"
```

Take a look at the https://github.com/meshapi/grpc-api-gateway-example repo, it has an example project using buf. Let me know if that helps. I'll keep this issue open for now.
